export const projects = [
  {
    title: 'Home',
    number: 0,
    lightBackground: '',
    background: '#041122',
    color: '#259073',
    brightness: '',
  },
  {
    title: 'Previsão do tempo',
    number: 1,
    lightBackground: '',
    background: '#06006f',
    color: '#eaeaea',
    brightness: '',
  },
  {
    title: 'Random Animals',
    number: 2,
    lightBackground: '',
    background: '#312305',
    color: '#0f4a0f',
  },
  {
    title: 'ruyTunes',
    number: 3,
    lightBackground: '',
    background: 'green',
    color: 'black',
    brightness: '',
  },
  {
    title: '',
    number: 4,
    lightBackground: '',
    background: '',
    color: '',
    brightness: '',
  },
  {
    title: '',
    number: 5,
    lightBackground: '',
    background: '',
    color: '',
    brightness: '',
  },
  {
    title: '',
    number: 6,
    lightBackground: '',
    background: '',
    color: '',
    brightness: '',
  }
]